"""initial migrations

Revision ID: 302cf30feaa0
Revises: 
Create Date: 2025-03-13 23:56:14.728886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302cf30feaa0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_shops',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('shop_owner', sa.String(), nullable=True),
    sa.Column('money_format', sa.String(), nullable=True),
    sa.Column('weight_unit', sa.String(), nullable=True),
    sa.Column('plan_display_name', sa.String(), nullable=True),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('has_discounts', sa.Boolean(), nullable=True),
    sa.Column('has_gift_cards', sa.Boolean(), nullable=True),
    sa.Column('primary_location_id', sa.Integer(), nullable=True),
    sa.Column('multi_location_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('enabled_presentment_currencies', sa.JSON(), nullable=True),
    sa.Column('shop_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id'),
    sa.UniqueConstraint('shop_id')
    )
    op.create_index(op.f('ix_shopify_shops_id'), 'shopify_shops', ['id'], unique=False)
    op.create_index(op.f('ix_shopify_shops_uid'), 'shopify_shops', ['uid'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'EMPLOYEE', 'MANAGER', 'OTHER', 'FRONTEND_ENGINEER', 'DEV_OPS_ENGINEER', 'BACKEND_ENGINEER', name='userrole'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shopify_shops_uid'), table_name='shopify_shops')
    op.drop_index(op.f('ix_shopify_shops_id'), table_name='shopify_shops')
    op.drop_table('shopify_shops')
    # ### end Alembic commands ###
