"""add ap id in the order model

Revision ID: 71d3b048e016
Revises: 77ce58df1ecb
Create Date: 2025-03-15 00:47:18.925754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d3b048e016'
down_revision: Union[str, None] = '77ce58df1ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('app_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'app_id')
    # ### end Alembic commands ###
